---
title: "NEET in Europe"
output: html_notebook
---

# Copyright 
- ikashnitsky.github.io 2017-07-18
- Accessing Eurostat data using the `eurostat` R package
- Young people neither in employment nor in education and training in Europe
- Ilya Kashnitsky, ilya.kashnitsky@gmail.com

---

# setting enviroment 
```{r, message=FALSE, warning=FALSE}
rm(list = ls(all = TRUE))

library(tidyverse)
library(lubridate)
library(forcats)
library(eurostat)
library(geofacet)
library(viridis)
library(ggthemes)
library(extrafont)

# download fertility rates for countries
neet <- get_eurostat("edat_lfse_22")
```

Find the needed dataset code 
http://ec.europa.eu/eurostat/web/regions/data/database

--- 

# dealing data
```{r}
using.df <- neet %>% 
  filter(geo %>% paste %>% nchar == 2,
         sex == "T", age == "Y18-24") %>%
  group_by(geo) %>% 
  mutate(avg = values %>% mean()) %>% 
  ungroup() %>%
  glimpse()
```

# Mapping
```{r, echo=TRUE, message=FALSE, warning=FALSE}
using.df %>% 
  ggplot(aes(x = time %>% year(),
             y = values))+
  geom_path(aes(group = 1))+
  geom_point(aes(fill = values), pch = 21)+
  scale_x_continuous(breaks = seq(2000, 2015, 5),
                     labels = c("2000", "'05", "'10", "'15"))+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 40))+
  scale_fill_viridis("NEET, %", option = "B")+
  facet_geo(~ geo, grid = "eu_grid1")+
  labs(x = "Year",
       y = "NEET, %",
       title = "Young people neither in employment nor in education and training in Europe",
       subtitle = "Data: Eurostat Regional Database, 2000-2016",
       caption = "ikashnitsky.github.io")+
  theme(axis.text = element_text(size = 10),
        panel.spacing.x = unit(1, "lines"),
        legend.position = c(0, 0),
        legend.justification = c(0, 0))
```

