---
title: "try_obesity in USA"
output: html_notebook

---
code source : https://datascienceplus.com/visualizing-obesity-across-united-states-by-using-data-from-wikipedia/
# Setting enviroment
```{r, message=FALSE, warning=FALSE}
## LOAD THE PACKAGES 
library(rvest)
library(ggplot2)
library(dplyr)
library(scales)
library(maps)
library(mapproj)
```

Download the data from Wikipedia
從wiki的表格中抓取

```{r}
obesity <- read_html("https://en.wikipedia.org/wiki/Obesity_in_the_United_States")

obesity <- obesity %>%
     html_nodes("table") %>%
     .[[2]]%>% #讀取第二個位置
     html_table(fill=T) %>% # fill with NA 
     print()
```
```{r}
## CLEAN THE DATA ####
str(obesity)
# remove the % and make the data numeric
for(i in 2:4){
     obesity[,i] = gsub("%", "", obesity[,i])
     obesity[,i] = as.numeric(obesity[,i])
}
# check data again
str(obesity)
names(obesity)
names(obesity) <- make.names(names(obesity)) 
names(obesity)
```
`make.names` 可以強迫符合句法，將空格以`.`取代

# Mapping
```{r}
# load the map data
states <- map_data("state") %>%  # 使用`maps`package 內建的資料
  select(-6) # 刪掉空欄位
str(states)
```

```{r}
# create a new variable name for state
obesity <- obesity %>%
  mutate(region = tolower(State.and.District.of.Columbia)) # `tolower` 全改為小寫

# merge data
obinstate <- states %>%
  full_join(obesity, by = "region") 

# making state names
statenames <- obinstate %>% 
  group_by(region) %>%
  summarise(
    long = mean(range(long)), 
    lat = mean(range(lat)), 
    group = mean(group), 
    Obese.adults = mean(Obese.adults), 
    Obese.children.and.adolescents = mean(Obese.children.and.adolescents)
  )
```

## Plot 
### Adult obesity
```{r}
# adults
obinstate %>%
  ggplot(aes(x = long, y = lat, group = group, fill = Obese.adults)) + 
  geom_polygon(color = "white") +
  scale_fill_gradient(name = "Percent", low = "#feceda", high = "#c81f49", guide = "colorbar",
                      na.value="black", breaks = pretty_breaks(n = 5)) +
  labs(title="Prevalence of Obesity in Adults") +
  geom_text(data=statenames, aes(x = long, y = lat, label = region), size=3) +
  coord_map()
```
### Children obesity
```{r}
# adults
obinstate %>%
  ggplot(aes(x = long, y = lat, group = group, fill = Obese.children.and.adolescents)) + 
  geom_polygon(color = "white") +
  scale_fill_gradient(name = "Percent", low = "#feceda", high = "#c81f49", guide = "colorbar",na.value="black", breaks = pretty_breaks(n = 5)) +
  labs(title="Prevalence of Obesity in Children") +
  scale_fill_gradient(name = "Percent", low = "#feceda", high = "#c81f49", guide = "colorbar",     na.value="black", breaks = pretty_breaks(n = 5)) +
  labs(title="Prevalence of Obesity in Adults") +
 geom_text(data=statenames, aes(x = long, y = lat, label = region), size=3) +
  coord_map()
```                 


